/**
 * Footer Component
 * 
 * Site footer with copyright, links, and disclaimer.
 * Contains navigation links and important legal/safety information.
 */

function Footer() {
    return (
        <footer className="bg-yellow-50 border-t border-yellow-100 text-sm text-center py-6 md:py-8 px-4">
            
            {/* Copyright and tech stack info */}
            <p className="mb-3 md:mb-4 text-stone-600 text-xs md:text-sm">
                © 2025 <a href="https://github.com/leorfernandes" className="text-stone-600 hover:underline hover:text-lime-600">Leo Fernandes</a> • Built with React, Vite, TailwindCSS, and OpenAI GPT-3.5
            </p>
            
            {/* Navigation and social links */}
            <div className="flex flex-col md:flex-row justify-center gap-2 md:gap-4 mb-3 md:mb-4">
                <a href="https://github.com/leorfernandes/ai-recipe-generator" className="text-stone-600 hover:underline hover:text-lime-600 text-xs md:text-sm" target="_blank" rel="noopener noreferrer">GitHub</a>
                <a href="https://linkedin.com/in/leonardodosreisfernandes" className="text-stone-600 hover:underline hover:text-lime-600 text-xs md:text-sm" target="_blank" rel="noopener noreferrer">LinkedIn</a>
                <a href="#hero" className="text-stone-600 hover:underline hover:text-lime-600 text-xs md:text-sm">Back to Top ↑</a>
            </div>
            
            {/* Legal disclaimer for AI-generated content */}
            <p className="text-xs md:text-sm text-stone-600 max-w-4xl mx-auto leading-relaxed">
                ⚠️ Disclaimer: This is a demo app for educational and portfolio purposes. Recipes are generated by an AI and may not be accurate, complete, or safe for all dietary needs. Always use your best judgment and consult a professional if you have dietary restrictions or allergies.
            </p>
        </footer>
    );
}

export default Footer;